import { Material, Category, Unit } from './types';

export const INITIAL_MATERIALS: Material[] = [
  {
    id: '1',
    name: 'Cemento Gris Argos Uso General 50kg',
    category: Category.CEMENTOS,
    supplier: 'Homecenter',
    price: 36900,
    currency: 'COP',
    unit: Unit.BULTO,
    lastUpdated: '2024-02-01',
    trend: 'stable',
    url: 'https://www.homecenter.com.co/homecenter-co/product/12838/cemento-gris-uso-general-50-kg-argos/12838/',
    history: []
  },
  {
    id: '2',
    name: 'Varilla Corrugada 1/2 pulgada x 6m grado 60',
    category: Category.ACEROS,
    supplier: 'Constructor Sodimac',
    price: 24500,
    currency: 'COP',
    unit: Unit.PIEZA,
    lastUpdated: '2024-02-05',
    trend: 'stable',
    history: []
  },
  {
    id: '3',
    name: 'Arena de Río lavada por metro cúbico',
    category: Category.ARENAS,
    supplier: 'Ferretería Local',
    price: 115000,
    currency: 'COP',
    unit: Unit.M3,
    lastUpdated: '2024-02-10',
    trend: 'stable',
    history: []
  },
  {
    id: '4',
    name: 'Ladrillo Tolete Común prensado 25x12x6',
    category: Category.LADRILLOS,
    supplier: 'Ladrillera Santa Fe',
    price: 1350,
    currency: 'COP',
    unit: Unit.PIEZA,
    lastUpdated: '2024-02-08',
    trend: 'stable',
    history: []
  },
  {
    id: '5',
    name: 'Tubo PVC Presión Pavco 1/2 pulgada RDE 21 6m',
    category: Category.PLOMERIA,
    supplier: 'Homecenter',
    price: 26900,
    currency: 'COP',
    unit: Unit.PIEZA,
    lastUpdated: '2024-02-11',
    trend: 'stable',
    history: []
  },
  {
    id: '6',
    name: 'Cable Eléctrico Nexans Cobre #12 AWG 100 metros',
    category: Category.ELECTRICO,
    supplier: 'Constructor Sodimac',
    price: 389000,
    currency: 'COP',
    unit: Unit.METRO,
    lastUpdated: '2024-02-09',
    trend: 'stable',
    history: []
  },
  {
    id: '7',
    name: 'Gravilla de Concreto por metro cúbico',
    category: Category.ARENAS,
    supplier: 'Ferretería Local',
    price: 140000,
    currency: 'COP',
    unit: Unit.M3,
    lastUpdated: '2024-02-01',
    trend: 'stable',
    history: []
  },
  {
    id: '8',
    name: 'Malla Electrosoldada 4mm 2.35x6m para refuerzo',
    category: Category.ACEROS,
    supplier: 'Constructor Sodimac',
    price: 158000,
    currency: 'COP',
    unit: Unit.PIEZA,
    lastUpdated: '2024-02-07',
    trend: 'stable',
    history: []
  },
  {
    id: '9',
    name: 'Bloque #5 (Tolete) 10x20x30cm estructural',
    category: Category.LADRILLOS,
    supplier: 'Ladrillera Local',
    price: 1850,
    currency: 'COP',
    unit: Unit.PIEZA,
    lastUpdated: '2024-02-03',
    trend: 'stable',
    history: []
  },
  {
    id: '10',
    name: 'Pintura Vinilo Blanco Koraza Pintuco (5 Galones)',
    category: Category.ACABADOS,
    supplier: 'Tienda Pintuco',
    price: 549900,
    currency: 'COP',
    unit: Unit.LITRO,
    lastUpdated: '2024-02-10',
    trend: 'stable',
    url: 'https://www.pintuco.com.co/productos/vinilo-koraza',
    history: []
  },
  {
    id: '11',
    name: 'Pegante Cerámica Coraza Pegacor Gris 25kg',
    category: Category.CEMENTOS,
    supplier: 'Easy Colombia',
    price: 28900,
    currency: 'COP',
    unit: Unit.BULTO,
    lastUpdated: '2024-02-04',
    trend: 'stable',
    history: []
  },
  {
    id: '12',
    name: 'Alambre Negro Calibre 18 para amarre',
    category: Category.ACEROS,
    supplier: 'Ferretería Samir',
    price: 8500,
    currency: 'COP',
    unit: Unit.KG,
    lastUpdated: '2024-02-02',
    trend: 'stable',
    history: []
  },
  {
    id: '13',
    name: 'Unión PVC Presión 1/2 pulgada Pavco soldable',
    category: Category.PLOMERIA,
    supplier: 'Homecenter',
    price: 1200,
    currency: 'COP',
    unit: Unit.PIEZA,
    lastUpdated: '2024-02-11',
    trend: 'stable',
    history: []
  },
  {
    id: '14',
    name: 'Tablero Eléctrico 12 Circuitos Schneider para empotrar',
    category: Category.ELECTRICO,
    supplier: 'Constructor Sodimac',
    price: 145900,
    currency: 'COP',
    unit: Unit.PIEZA,
    lastUpdated: '2024-02-10',
    trend: 'stable',
    history: []
  },
  {
    id: '15',
    name: 'Cerámica Piso 45x45cm Corona (Caja 1.5m2)',
    category: Category.ACABADOS,
    supplier: 'Corona',
    price: 42500,
    currency: 'COP',
    unit: Unit.M3,
    lastUpdated: '2024-02-08',
    trend: 'stable',
    history: []
  },
  {
    id: '16',
    name: 'Ladrillo H-10 Bloque Hueco estructural',
    category: Category.LADRILLOS,
    supplier: 'Ladrillera Local',
    price: 1450,
    currency: 'COP',
    unit: Unit.PIEZA,
    lastUpdated: '2024-02-05',
    trend: 'stable',
    history: []
  },
  {
    id: '17',
    name: 'Sika-1 Aditivo Impermeabilizante 1 Galón',
    category: Category.CEMENTOS,
    supplier: 'Homecenter',
    price: 34900,
    currency: 'COP',
    unit: Unit.LITRO,
    lastUpdated: '2024-02-09',
    trend: 'stable',
    history: []
  },
  {
    id: '18',
    name: 'Tabla de Madera Pino Patula 3 metros',
    category: Category.MADERA,
    supplier: 'Deposito Local',
    price: 18000,
    currency: 'COP',
    unit: Unit.PIEZA,
    lastUpdated: '2024-02-11',
    trend: 'stable',
    history: []
  },
  {
    id: '19',
    name: 'Pala Redonda Herragro Profesional mango largo',
    category: Category.HERRAMIENTAS,
    supplier: 'Homecenter',
    price: 45900,
    currency: 'COP',
    unit: Unit.PIEZA,
    lastUpdated: '2024-02-11',
    trend: 'stable',
    history: []
  },
  {
    id: '20',
    name: 'Carretilla de 5.5 Pies Cúbicos llanta neumática',
    category: Category.HERRAMIENTAS,
    supplier: 'Constructor Sodimac',
    price: 189900,
    currency: 'COP',
    unit: Unit.PIEZA,
    lastUpdated: '2024-02-11',
    trend: 'stable',
    history: []
  }
];

export const SUPPLIERS = [
  'Homecenter',
  'Constructor Sodimac',
  'Easy Colombia',
  'Cemex Colombia',
  'Argos',
  'Ferretería Samir',
  'Ladrillera Santa Fe',
  'Ferretería Local',
  'MercadoLibre Colombia',
  'Tienda Pintuco',
  'Pavco Wavin',
  'Corona'
];